/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTerminalRouteImport } from './routes/_authenticated/terminal'
import { Route as AuthenticatedTedarikcilerRouteImport } from './routes/_authenticated/tedarikciler'
import { Route as AuthenticatedStokRouteImport } from './routes/_authenticated/stok'
import { Route as AuthenticatedSatislarRouteImport } from './routes/_authenticated/satislar'
import { Route as AuthenticatedRaporlarRouteImport } from './routes/_authenticated/raporlar'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedMusterilerRouteImport } from './routes/_authenticated/musteriler'
import { Route as AuthenticatedKullanicilarRouteImport } from './routes/_authenticated/kullanicilar'
import { Route as AuthenticatedBarkodRouteImport } from './routes/_authenticated/barkod'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTerminalRoute = AuthenticatedTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTedarikcilerRoute =
  AuthenticatedTedarikcilerRouteImport.update({
    id: '/tedarikciler',
    path: '/tedarikciler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStokRoute = AuthenticatedStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSatislarRoute = AuthenticatedSatislarRouteImport.update({
  id: '/satislar',
  path: '/satislar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRaporlarRoute = AuthenticatedRaporlarRouteImport.update({
  id: '/raporlar',
  path: '/raporlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMusterilerRoute = AuthenticatedMusterilerRouteImport.update({
  id: '/musteriler',
  path: '/musteriler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKullanicilarRoute =
  AuthenticatedKullanicilarRouteImport.update({
    id: '/kullanicilar',
    path: '/kullanicilar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBarkodRoute = AuthenticatedBarkodRouteImport.update({
  id: '/barkod',
  path: '/barkod',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/barkod': typeof AuthenticatedBarkodRoute
  '/kullanicilar': typeof AuthenticatedKullanicilarRoute
  '/musteriler': typeof AuthenticatedMusterilerRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/raporlar': typeof AuthenticatedRaporlarRoute
  '/satislar': typeof AuthenticatedSatislarRoute
  '/stok': typeof AuthenticatedStokRoute
  '/tedarikciler': typeof AuthenticatedTedarikcilerRoute
  '/terminal': typeof AuthenticatedTerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/barkod': typeof AuthenticatedBarkodRoute
  '/kullanicilar': typeof AuthenticatedKullanicilarRoute
  '/musteriler': typeof AuthenticatedMusterilerRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/raporlar': typeof AuthenticatedRaporlarRoute
  '/satislar': typeof AuthenticatedSatislarRoute
  '/stok': typeof AuthenticatedStokRoute
  '/tedarikciler': typeof AuthenticatedTedarikcilerRoute
  '/terminal': typeof AuthenticatedTerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/barkod': typeof AuthenticatedBarkodRoute
  '/_authenticated/kullanicilar': typeof AuthenticatedKullanicilarRoute
  '/_authenticated/musteriler': typeof AuthenticatedMusterilerRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/raporlar': typeof AuthenticatedRaporlarRoute
  '/_authenticated/satislar': typeof AuthenticatedSatislarRoute
  '/_authenticated/stok': typeof AuthenticatedStokRoute
  '/_authenticated/tedarikciler': typeof AuthenticatedTedarikcilerRoute
  '/_authenticated/terminal': typeof AuthenticatedTerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/barkod'
    | '/kullanicilar'
    | '/musteriler'
    | '/panel'
    | '/raporlar'
    | '/satislar'
    | '/stok'
    | '/tedarikciler'
    | '/terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/barkod'
    | '/kullanicilar'
    | '/musteriler'
    | '/panel'
    | '/raporlar'
    | '/satislar'
    | '/stok'
    | '/tedarikciler'
    | '/terminal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/barkod'
    | '/_authenticated/kullanicilar'
    | '/_authenticated/musteriler'
    | '/_authenticated/panel'
    | '/_authenticated/raporlar'
    | '/_authenticated/satislar'
    | '/_authenticated/stok'
    | '/_authenticated/tedarikciler'
    | '/_authenticated/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/terminal': {
      id: '/_authenticated/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AuthenticatedTerminalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tedarikciler': {
      id: '/_authenticated/tedarikciler'
      path: '/tedarikciler'
      fullPath: '/tedarikciler'
      preLoaderRoute: typeof AuthenticatedTedarikcilerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stok': {
      id: '/_authenticated/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof AuthenticatedStokRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/satislar': {
      id: '/_authenticated/satislar'
      path: '/satislar'
      fullPath: '/satislar'
      preLoaderRoute: typeof AuthenticatedSatislarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/raporlar': {
      id: '/_authenticated/raporlar'
      path: '/raporlar'
      fullPath: '/raporlar'
      preLoaderRoute: typeof AuthenticatedRaporlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/musteriler': {
      id: '/_authenticated/musteriler'
      path: '/musteriler'
      fullPath: '/musteriler'
      preLoaderRoute: typeof AuthenticatedMusterilerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kullanicilar': {
      id: '/_authenticated/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/kullanicilar'
      preLoaderRoute: typeof AuthenticatedKullanicilarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barkod': {
      id: '/_authenticated/barkod'
      path: '/barkod'
      fullPath: '/barkod'
      preLoaderRoute: typeof AuthenticatedBarkodRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBarkodRoute: typeof AuthenticatedBarkodRoute
  AuthenticatedKullanicilarRoute: typeof AuthenticatedKullanicilarRoute
  AuthenticatedMusterilerRoute: typeof AuthenticatedMusterilerRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedRaporlarRoute: typeof AuthenticatedRaporlarRoute
  AuthenticatedSatislarRoute: typeof AuthenticatedSatislarRoute
  AuthenticatedStokRoute: typeof AuthenticatedStokRoute
  AuthenticatedTedarikcilerRoute: typeof AuthenticatedTedarikcilerRoute
  AuthenticatedTerminalRoute: typeof AuthenticatedTerminalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBarkodRoute: AuthenticatedBarkodRoute,
  AuthenticatedKullanicilarRoute: AuthenticatedKullanicilarRoute,
  AuthenticatedMusterilerRoute: AuthenticatedMusterilerRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedRaporlarRoute: AuthenticatedRaporlarRoute,
  AuthenticatedSatislarRoute: AuthenticatedSatislarRoute,
  AuthenticatedStokRoute: AuthenticatedStokRoute,
  AuthenticatedTedarikcilerRoute: AuthenticatedTedarikcilerRoute,
  AuthenticatedTerminalRoute: AuthenticatedTerminalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
